Metrics/LineLength:
  Max: 180

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent